export const MARKDOWN_FEATURES = {
  code: "markdown.code",
  emphasis: "markdown.emphasis",
  heading: "markdown.heading",
  inlineCode: "markdown.inline-code",
  link: "markdown.link",
  list: "markdown.list",
  paragraph: "markdown.paragraph",
  quote: "markdown.quote",
  thematicBreak: "markdown.thematic-break",
  gfmStrikethrough: "gfm.strikethrough",
  gfmTable: "gfm.table",
  gfmTaskList: "gfm.task-list",
  gfmAutolink: "gfm.autolink",
  gfmTagFilter: "gfm.tag-filter",
  highlight: "eidos.highlight",
  math: "efm.math",
  image: "efm.image",
  footnote: "efm.footnote",
  frontmatter: "efm.frontmatter",
  rawHtml: "efm.raw-html",
  reference: "efm.reference",
  sourceRangeEditing: "editor.source-range-editing",
  obsidianHighlight: "obsidian.highlight",
  obsidianMath: "obsidian.math",
  obsidianAttachment: "obsidian.attachment",
  obsidianFootnote: "obsidian.footnote",
  obsidianProperties: "obsidian.properties",
  obsidianRawHtml: "obsidian.raw-html",
  obsidianReference: "obsidian.reference",
  obsidianWikilink: "obsidian.wikilink",
  obsidianEmbed: "obsidian.embed",
  obsidianBlockId: "obsidian.block-id",
  obsidianCallout: "obsidian.callout",
  obsidianComment: "obsidian.comment",
  obsidianTag: "obsidian.tag",
  obsidianInlineFootnote: "obsidian.inline-footnote",
} as const

export type MarkdownFeatureId =
  (typeof MARKDOWN_FEATURES)[keyof typeof MARKDOWN_FEATURES]
