// This file is auto-generated by scripts/compile-ui-files.ts on 2025-05-07T17:55:47.150Z
// DO NOT EDIT THIS FILE MANUALLY
export const uiComponentsDependencies = {
  "aspect-ratio": {
    "thirdPartyLibs": [
      "@radix-ui/react-aspect-ratio"
    ],
    "uiLibs": []
  },
  "alert-dialog": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-alert-dialog",
      "@radix-ui/react-slot",
      "class-variance-authority"
    ],
    "uiLibs": [
      "button"
    ]
  },
  "pagination": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-icons",
      "@radix-ui/react-slot",
      "class-variance-authority"
    ],
    "uiLibs": [
      "button"
    ]
  },
  "tabs": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-tabs"
    ],
    "uiLibs": []
  },
  "card": {
    "thirdPartyLibs": [
      "react"
    ],
    "uiLibs": []
  },
  "slider": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-slider"
    ],
    "uiLibs": []
  },
  "popover": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-popover"
    ],
    "uiLibs": []
  },
  "progress": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-progress"
    ],
    "uiLibs": []
  },
  "toaster": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-toast",
      "class-variance-authority",
      "@radix-ui/react-icons"
    ],
    "uiLibs": [
      "toast"
    ]
  },
  "input-otp": {
    "thirdPartyLibs": [
      "react",
      "input-otp",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "chart": {
    "thirdPartyLibs": [
      "react",
      "recharts"
    ],
    "uiLibs": []
  },
  "hover-card": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-hover-card"
    ],
    "uiLibs": []
  },
  "sheet": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-dialog",
      "class-variance-authority",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "scroll-area": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-scroll-area"
    ],
    "uiLibs": []
  },
  "resizable": {
    "thirdPartyLibs": [
      "react-resizable-panels",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "label": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-label",
      "class-variance-authority"
    ],
    "uiLibs": []
  },
  "sonner": {
    "thirdPartyLibs": [
      "next-themes",
      "sonner"
    ],
    "uiLibs": []
  },
  "navigation-menu": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-navigation-menu",
      "class-variance-authority",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "accordion": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-accordion",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "drawer": {
    "thirdPartyLibs": [
      "react",
      "vaul"
    ],
    "uiLibs": []
  },
  "tooltip": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-tooltip"
    ],
    "uiLibs": []
  },
  "alert": {
    "thirdPartyLibs": [
      "react",
      "class-variance-authority"
    ],
    "uiLibs": []
  },
  "use-toast": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-toast",
      "class-variance-authority",
      "@radix-ui/react-icons"
    ],
    "uiLibs": [
      "toast"
    ]
  },
  "switch": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-switch"
    ],
    "uiLibs": []
  },
  "calendar": {
    "thirdPartyLibs": [
      "react",
      "react-day-picker",
      "@radix-ui/react-icons",
      "@radix-ui/react-slot",
      "class-variance-authority"
    ],
    "uiLibs": [
      "button"
    ]
  },
  "breadcrumb": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-slot",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "radio-group": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-radio-group",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "command": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-dialog",
      "@radix-ui/react-icons",
      "cmdk"
    ],
    "uiLibs": [
      "dialog"
    ]
  },
  "toggle-group": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-toggle-group",
      "class-variance-authority",
      "@radix-ui/react-toggle"
    ],
    "uiLibs": [
      "toggle"
    ]
  },
  "avatar": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-avatar"
    ],
    "uiLibs": []
  },
  "menubar": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-menubar",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "dialog": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-dialog",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "badge": {
    "thirdPartyLibs": [
      "react",
      "class-variance-authority"
    ],
    "uiLibs": []
  },
  "sidebar": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-slot",
      "class-variance-authority",
      "@radix-ui/react-icons",
      "@radix-ui/react-separator",
      "@radix-ui/react-dialog",
      "@radix-ui/react-tooltip"
    ],
    "uiLibs": [
      "button",
      "input",
      "separator",
      "sheet",
      "skeleton",
      "tooltip"
    ]
  },
  "table": {
    "thirdPartyLibs": [
      "react"
    ],
    "uiLibs": []
  },
  "separator": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-separator"
    ],
    "uiLibs": []
  },
  "button": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-slot",
      "class-variance-authority"
    ],
    "uiLibs": []
  },
  "toggle": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-toggle",
      "class-variance-authority"
    ],
    "uiLibs": []
  },
  "toast": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-toast",
      "class-variance-authority",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "checkbox": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-checkbox",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "collapsible": {
    "thirdPartyLibs": [
      "@radix-ui/react-collapsible"
    ],
    "uiLibs": []
  },
  "dropdown-menu": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-dropdown-menu",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "select": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-select",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "textarea": {
    "thirdPartyLibs": [
      "react"
    ],
    "uiLibs": []
  },
  "input": {
    "thirdPartyLibs": [
      "react"
    ],
    "uiLibs": []
  },
  "skeleton": {
    "thirdPartyLibs": [],
    "uiLibs": []
  },
  "context-menu": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-context-menu",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "form": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-label",
      "@radix-ui/react-slot",
      "react-hook-form",
      "class-variance-authority"
    ],
    "uiLibs": [
      "label"
    ]
  },
  "carousel": {
    "thirdPartyLibs": [
      "react",
      "embla-carousel-react",
      "@radix-ui/react-icons",
      "@radix-ui/react-slot",
      "class-variance-authority"
    ],
    "uiLibs": [
      "button"
    ]
  }
}