import { FieldType } from "./const"

const computedFieldTypes = [FieldType.Formula, FieldType.Lookup, FieldType.Link]
const autoGeneratedFieldTypes = [
  FieldType.CreatedBy,
  FieldType.LastEditedBy,
  FieldType.CreatedTime,
  FieldType.LastEditedTime,
]
export const isComputedField = (columnType: FieldType) => {
  return computedFieldTypes.includes(columnType)
}

export const isAutoGeneratedField = (columnType: FieldType) => {
  return autoGeneratedFieldTypes.includes(columnType)
}

/**
 * Smart split that only splits on commas when followed by file/URL prefixes.
 * This preserves commas within filenames and data URIs.
 *
 * The function treats a comma as a separator only when it's followed by:
 * - `/` (file paths like /files/...)
 * - `http://` or `https://` (network URLs)
 * - `data:` (data URIs)
 *
 * Commas within data URIs (after the initial `data:mime;base64,` part) are preserved.
 *
 * @param str - The comma-separated string to split
 * @returns Array of file paths with commas preserved in filenames
 *
 * @example
 * smartSplitFilePaths("/files/Song,Artist - Title.mp3")
 * // Returns: ["/files/Song,Artist - Title.mp3"]
 *
 * @example
 * smartSplitFilePaths("/files/Song,Artist.mp3, /files/Another.jpg")
 * // Returns: ["/files/Song,Artist.mp3", "/files/Another.jpg"]
 *
 * @example
 * smartSplitFilePaths("https://example.com/file,with,commas.jpg, data:image/png;base64,iVBORw...")
 * // Returns: ["https://example.com/file,with,commas.jpg", "data:image/png;base64,iVBORw..."]
 *
 * @example
 * smartSplitFilePaths("data:image/jpg;base64,/9j/4AAQSkZJRgABAgAAAQ,ABAAD/2wBDAA")
 * // Returns: ["data:image/jpg;base64,/9j/4AAQSkZJRgABAgAAAQ,ABAAD/2wBDAA"]
 */
export function smartSplitFilePaths(str: string): string[] {
  if (!str) return []

  const result: string[] = []
  let currentPath = ""
  let i = 0

  while (i < str.length) {
    const char = str[i]

    if (char === ",") {
      // Look ahead to see if this comma should be a separator
      let nextIndex = i + 1
      const hasSpaceAfterComma =
        nextIndex < str.length && /\s/.test(str[nextIndex])

      // Skip whitespace after comma
      while (nextIndex < str.length && /\s/.test(str[nextIndex])) {
        nextIndex++
      }

      // Check if next content starts with /, http://, https://, or data:
      const remaining = str.slice(nextIndex)
      const isNewFile =
        remaining.startsWith("/") ||
        remaining.startsWith("http://") ||
        remaining.startsWith("https://") ||
        remaining.startsWith("data:")

      // Check if we're currently inside a data URI
      const inDataUri = currentPath.trim().startsWith("data:")

      // Split if:
      // 1. There's a space after the comma AND it's followed by a new file prefix, OR
      // 2. Not in a data URI and followed by a new file prefix
      const shouldSplit =
        (hasSpaceAfterComma && isNewFile) || (isNewFile && !inDataUri)

      if (shouldSplit) {
        // This comma is a separator
        const trimmed = currentPath.trim()
        if (trimmed) {
          result.push(trimmed)
        }
        currentPath = ""
        i = nextIndex // Skip the comma and whitespace
        continue
      } else {
        // This comma is part of the filename or data URI data
        currentPath += char
      }
    } else {
      currentPath += char
    }

    i++
  }

  // Add the last path
  const trimmed = currentPath.trim()
  if (trimmed) {
    result.push(trimmed)
  }

  return result
}
