import type { EditorThemeClasses } from "lexical"

/** Class-only theme. Consumers can replace any visual using CSS variables. */
export const MARKDOWN_EDITOR_THEME: EditorThemeClasses = {
  code: "eidos-md-code-block",
  codeHighlight: {
    atrule: "eidos-md-token-keyword",
    attr: "eidos-md-token-property",
    boolean: "eidos-md-token-number",
    builtin: "eidos-md-token-builtin",
    cdata: "eidos-md-token-comment",
    char: "eidos-md-token-string",
    class: "eidos-md-token-class",
    comment: "eidos-md-token-comment",
    constant: "eidos-md-token-number",
    deleted: "eidos-md-token-deleted",
    doctype: "eidos-md-token-comment",
    entity: "eidos-md-token-operator",
    function: "eidos-md-token-function",
    important: "eidos-md-token-keyword",
    inserted: "eidos-md-token-inserted",
    keyword: "eidos-md-token-keyword",
    namespace: "eidos-md-token-muted",
    number: "eidos-md-token-number",
    operator: "eidos-md-token-operator",
    prolog: "eidos-md-token-comment",
    property: "eidos-md-token-property",
    punctuation: "eidos-md-token-muted",
    regex: "eidos-md-token-regex",
    selector: "eidos-md-token-selector",
    string: "eidos-md-token-string",
    symbol: "eidos-md-token-number",
    tag: "eidos-md-token-tag",
    url: "eidos-md-token-link",
    variable: "eidos-md-token-variable",
  },
  heading: {
    h1: "eidos-md-heading eidos-md-heading-h1",
    h2: "eidos-md-heading eidos-md-heading-h2",
    h3: "eidos-md-heading eidos-md-heading-h3",
    h4: "eidos-md-heading eidos-md-heading-h4",
    h5: "eidos-md-heading eidos-md-heading-h5",
    h6: "eidos-md-heading eidos-md-heading-h6",
  },
  hr: "eidos-md-rule",
  hrSelected: "eidos-md-rule-selected",
  image: "eidos-md-image-node",
  indent: "eidos-md-indent",
  link: "eidos-md-link",
  list: {
    checklist: "eidos-md-check-list",
    listitem: "eidos-md-list-item",
    listitemChecked: "eidos-md-list-item-checked",
    listitemUnchecked: "eidos-md-list-item-unchecked",
    nested: {
      list: "eidos-md-nested-list",
      listitem: "eidos-md-nested-list-item",
    },
    ol: "eidos-md-list eidos-md-ordered-list",
    ul: "eidos-md-list eidos-md-unordered-list",
  },
  ltr: "eidos-md-ltr",
  paragraph: "eidos-md-paragraph",
  quote: "eidos-md-quote",
  root: "eidos-md-content",
  rtl: "eidos-md-rtl",
  table: "eidos-md-table",
  tableCell: "eidos-md-table-cell",
  tableCellHeader: "eidos-md-table-cell eidos-md-table-cell-header",
  tableRow: "eidos-md-table-row",
  tableScrollableWrapper: "eidos-md-table-scroll",
  tableSelected: "eidos-md-table-selected",
  text: {
    bold: "eidos-md-bold",
    code: "eidos-md-inline-code",
    italic: "eidos-md-italic",
    strikethrough: "eidos-md-strikethrough",
  },
  wikiLink: "eidos-md-wiki-link-node",
}
