[workspace]
resolver = "2"
members = ["apps/cli", "crates/*"]
default-members = ["apps/cli"]

[workspace.dependencies]
eidos-file-core = { path = "crates/eidos-file-core" }
eidos-runtime-host = { path = "crates/eidos-runtime-host", default-features = false }
eidos-publish = { path = "crates/eidos-publish" }
rusqlite = { version = "0.38", features = ["bundled"] }
graft-sdk = { git = "https://github.com/eidos-space/graft", rev = "5c99ad07ee1af7b66432c94c6e919c7faa5cacd5", features = [
  "bundled-sqlite",
] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
