/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 082b96d7e2d8b935c317c8300f62f6ea)
interface __BaseEnv_Env {
	GRAFT_OBJECTS: R2Bucket;
	AUTH_USERINFO_URL: "https://staging.eidos.space/api/sync/userinfo" | "https://eidos.space/api/sync/userinfo";
	PUBLIC_REMOTE_ORIGIN: "https://sync-staging.eidos.space" | "https://sync.eidos.space";
	SYNC_ACCESS_ENFORCEMENT: "enforce" | "off";
	SYNC_QUOTA_ENFORCEMENT: "enforce" | "shadow";
	GRAFT_REPOSITORIES: DurableObjectNamespace<import("./src/index").RepositoryDurableObject>;
	GRAFT_DIRECTORY: DurableObjectNamespace<import("./src/index").RepositoryDirectoryDurableObject>;
	GRAFT_USAGE: DurableObjectNamespace<import("./src/index").SyncUsageDurableObject>;
	EIDOS_ACCOUNT: Fetcher /* eidos-space-staging */ | Fetcher /* eidos-space */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RepositoryDurableObject" | "RepositoryDirectoryDurableObject" | "SyncUsageDurableObject";
	}
	interface StagingEnv {
		GRAFT_OBJECTS: R2Bucket;
		AUTH_USERINFO_URL: "https://staging.eidos.space/api/sync/userinfo";
		PUBLIC_REMOTE_ORIGIN: "https://sync-staging.eidos.space";
		SYNC_ACCESS_ENFORCEMENT: "enforce";
		SYNC_QUOTA_ENFORCEMENT: "enforce";
		GRAFT_REPOSITORIES: DurableObjectNamespace<import("./src/index").RepositoryDurableObject>;
		GRAFT_DIRECTORY: DurableObjectNamespace<import("./src/index").RepositoryDirectoryDurableObject>;
		GRAFT_USAGE: DurableObjectNamespace<import("./src/index").SyncUsageDurableObject>;
		EIDOS_ACCOUNT: Fetcher /* eidos-space-staging */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_USERINFO_URL" | "PUBLIC_REMOTE_ORIGIN" | "SYNC_ACCESS_ENFORCEMENT" | "SYNC_QUOTA_ENFORCEMENT">> {}
}
