import { defineConfig } from "tsdown"

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/eidos-file-data-grid.tsx",
    "src/eidos-file-editor-view.tsx",
    "src/plugin.tsx",
    "src/platform.tsx",
    "src/plugins/gallery.tsx",
    "src/plugins/kanban.tsx",
    "src/plugins/csv-import.tsx",
    "src/eidos-file-gallery-view.tsx",
    "src/eidos-file-kanban-view.tsx",
    "src/eidos-file-record-card.tsx",
    "src/eidos-file-record-card-layout.ts",
    "src/eidos-file-record-delete-dialog.tsx",
    "src/eidos-file-row-window.ts",
    "src/eidos-file-virtual-scroll.ts",
    "src/eidos-file-error-message.ts",
    "src/use-eidos-file-record-inspector-row.ts",
    "src/ui/alert-dialog.tsx",
    "src/ui/dropdown-menu.tsx",
    "src/ui/kanban.tsx",
    "src/eidos-file-editor-chrome.tsx",
    "src/eidos-file-csv-import-popover.tsx",
    "src/eidos-file-csv-operation-progress.tsx",
    "src/eidos-file-sheet-create-popover.tsx",
    "src/eidos-file-sheet-tabs.tsx",
    "src/eidos-file-view-selector.tsx",
    "src/eidos-file-view-tabs.tsx",
    "src/eidos-file-query-toolbar.tsx",
    "src/eidos-file-field-create-popover.tsx",
    "src/eidos-file-field-type-picker.tsx",
    "src/eidos-file-formula-composer.tsx",
    "src/eidos-file-derived-field-editor.tsx",
    "src/context.tsx",
  ],
  format: "esm",
  dts: true,
  sourcemap: true,
  clean: true,
  deps: {
    neverBundle: [
      "react",
      "react-dom",
      "react/jsx-runtime",
      "@eidos.space/eidos-file",
      "@glideapps/glide-data-grid",
      "@tanstack/react-virtual",
    ],
  },
})
