/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1d67083ee67be345f352a33c00e9700b)
interface __BaseEnv_Env {
  PUBLISH_OBJECTS: R2Bucket
  ASSETS: Fetcher
  AUTH_USERINFO_URL:
    | "https://staging.eidos.space/api/publish/userinfo"
    | "https://eidos.space/api/publish/userinfo"
  CONTROL_HOST: "publish-staging.eidos.space" | "publish.eidos.space"
  PUBLISH_ROOT: "eidos.ink"
  PUBLISH_HOST_LABEL_SUFFIX: "-staging" | ""
  RELAY_CONTROL_HOST: "relay-staging.eidos.ink" | "relay.eidos.ink"
  ORCHESTRATION_MODE: "workflow"
  RUNTIME_SHARD_COUNT: "2" | "8"
  RUNTIME_MAX_ACTIVE_VERSIONS: "6"
  RUNTIME_MAX_CACHE_BYTES: "3221225472"
  RUNTIME_MAX_INFLIGHT_REQUESTS: "32"
  TENANT_LOCATORS: DurableObjectNamespace<
    import("./src/index").TenantLocatorDurableObject
  >
  PUBLIC_SITE_CLAIMS: DurableObjectNamespace<
    import("./src/index").PublicSiteClaimDurableObject
  >
  PUBLISH_TENANTS: DurableObjectNamespace<import("./src/index").PublishTenant>
  PUBLISH_HANDLES: DurableObjectNamespace<
    import("./src/index").PublishHandleDurableObject
  >
  FORM_INBOXES: DurableObjectNamespace<
    import("./src/index").FormInboxDurableObject
  >
  EIDOS_RUNTIMES: DurableObjectNamespace<
    import("./src/index").EidosRuntimeContainer
  >
  EIDOS_ACCOUNT: Fetcher /* eidos-space-staging */ | Fetcher /* eidos-space */
  EIDOS_RELAY:
    | Fetcher /* eidos-file-relay-staging */
    | Fetcher /* eidos-file-relay */
  PUBLISH_WORKFLOW: Workflow<
    Parameters<import("./src/index").PublishWorkflow["run"]>[0]["payload"]
  >
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index")
    durableNamespaces:
      | "TenantLocatorDurableObject"
      | "PublicSiteClaimDurableObject"
      | "PublishHandleDurableObject"
      | "PublishTenant"
      | "FormInboxDurableObject"
      | "EidosRuntimeContainer"
  }
  interface StagingEnv {
    PUBLISH_OBJECTS: R2Bucket
    ASSETS: Fetcher
    AUTH_USERINFO_URL: "https://staging.eidos.space/api/publish/userinfo"
    CONTROL_HOST: "publish-staging.eidos.space"
    PUBLISH_ROOT: "eidos.ink"
    PUBLISH_HOST_LABEL_SUFFIX: "-staging"
    RELAY_CONTROL_HOST: "relay-staging.eidos.ink"
    ORCHESTRATION_MODE: "workflow"
    RUNTIME_SHARD_COUNT: "2"
    RUNTIME_MAX_ACTIVE_VERSIONS: "6"
    RUNTIME_MAX_CACHE_BYTES: "3221225472"
    RUNTIME_MAX_INFLIGHT_REQUESTS: "32"
    TENANT_LOCATORS: DurableObjectNamespace<
      import("./src/index").TenantLocatorDurableObject
    >
    PUBLIC_SITE_CLAIMS: DurableObjectNamespace<
      import("./src/index").PublicSiteClaimDurableObject
    >
    PUBLISH_TENANTS: DurableObjectNamespace<import("./src/index").PublishTenant>
    PUBLISH_HANDLES: DurableObjectNamespace<
      import("./src/index").PublishHandleDurableObject
    >
    FORM_INBOXES: DurableObjectNamespace<
      import("./src/index").FormInboxDurableObject
    >
    EIDOS_RUNTIMES: DurableObjectNamespace<
      import("./src/index").EidosRuntimeContainer
    >
    EIDOS_ACCOUNT: Fetcher /* eidos-space-staging */
    EIDOS_RELAY: Fetcher /* eidos-file-relay-staging */
    PUBLISH_WORKFLOW: Workflow<
      Parameters<import("./src/index").PublishWorkflow["run"]>[0]["payload"]
    >
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "AUTH_USERINFO_URL"
      | "CONTROL_HOST"
      | "PUBLISH_ROOT"
      | "PUBLISH_HOST_LABEL_SUFFIX"
      | "RELAY_CONTROL_HOST"
      | "ORCHESTRATION_MODE"
      | "RUNTIME_SHARD_COUNT"
      | "RUNTIME_MAX_ACTIVE_VERSIONS"
      | "RUNTIME_MAX_CACHE_BYTES"
      | "RUNTIME_MAX_INFLIGHT_REQUESTS"
    >
  > {}
}
