use clap::{Args, ValueEnum};
use std::path::PathBuf;

#[derive(Debug, Args)]
pub struct PublishArgs {
    /// Local file to publish.
    pub file: PathBuf,
    /// Original Space-relative file path, independent of the publication slug.
    #[arg(long, value_name = "PATH")]
    pub source_path: Option<String>,
    /// Render the source using this .eidos-plugin package.
    #[arg(
        long,
        value_name = "PACKAGE",
        requires = "plugin_view",
        conflicts_with = "form_view"
    )]
    pub plugin: Option<PathBuf>,
    /// File View ID inside --plugin.
    #[arg(long, value_name = "VIEW_ID", requires = "plugin")]
    pub plugin_view: Option<String>,
    /// Publish one Form View from an Eidos File instead of the whole File.
    #[arg(long, value_name = "VIEW_ID_OR_NAME")]
    pub form_view: Option<String>,
    /// Who may submit a published Form.
    #[arg(long, value_enum, requires = "form_view")]
    pub form_respondents: Option<FormRespondentAccessArg>,
    /// Allow each signed-in eidos.space user to submit only once.
    #[arg(long, requires = "form_view")]
    pub one_response_per_user: bool,
    /// Filesystem root used to resolve relative attachments.
    #[arg(long, value_name = "DIR", hide = true)]
    pub attachment_root: Option<PathBuf>,
    /// Graft SQLite page delta generated by Eidos Lite.
    #[arg(long, value_name = "FILE", hide = true, requires = "graft_base_sha256")]
    pub graft_delta: Option<PathBuf>,
    /// SHA-256 of the previously published Eidos source used as the delta base.
    #[arg(long, value_name = "SHA256", hide = true, requires = "graft_delta")]
    pub graft_base_sha256: Option<String>,
    /// Tenant-local URL path for this published resource.
    #[arg(long)]
    pub slug: String,
    /// Public or private viewer access. Hosted publishing requires Publish.
    #[arg(long, value_enum, default_value_t = PublishVisibilityArg::Public)]
    pub visibility: PublishVisibilityArg,
    /// Protect this Publication with a password. The CLI prompts without echo.
    #[arg(long, conflicts_with = "remove_password")]
    pub password: bool,
    /// Native hosts pass the password in memory, without environment or terminal input.
    #[arg(skip)]
    pub password_value: Option<String>,
    /// Remove password protection and make this Publication public.
    #[arg(long, conflicts_with = "password")]
    pub remove_password: bool,
    /// Hide the Built with Eidos badge.
    #[arg(long, conflicts_with = "show_branding")]
    pub hide_branding: bool,
    /// Show the Built with Eidos badge on this Publication.
    #[arg(long, conflicts_with = "hide_branding")]
    pub show_branding: bool,
    /// Create a ready Version without moving the Publication pointer.
    #[arg(long)]
    pub no_activate: bool,
    /// Publish control origin.
    #[arg(
        long,
        env = "EIDOS_PUBLISH_ORIGIN",
        default_value = "https://publish.eidos.space"
    )]
    pub publish_origin: String,
    /// Publish CLI key. Prefer the EIDOS_PUBLISH_TOKEN environment variable.
    #[arg(long, env = "EIDOS_PUBLISH_TOKEN", hide_env_values = true)]
    pub token: String,
    /// Maximum time to wait for validation, Runtime preparation, and activation.
    #[arg(long, default_value_t = 1_800)]
    pub wait_seconds: u64,
    /// Emit newline-delimited Publish progress events to stderr.
    #[arg(long, hide = true)]
    pub progress_json: bool,
    /// Optional client environment metadata JSON (e.g. from Eidos Lite).
    #[arg(long, value_name = "JSON", hide = true)]
    pub client_metadata_json: Option<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
#[value(rename_all = "lower")]
pub enum PublishVisibilityArg {
    Public,
    Private,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
#[value(rename_all = "kebab-case")]
pub enum FormRespondentAccessArg {
    Anyone,
    SignedIn,
}

impl FormRespondentAccessArg {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Anyone => "anyone",
            Self::SignedIn => "signed_in",
        }
    }
}

impl PublishVisibilityArg {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Public => "public",
            Self::Private => "private",
        }
    }
}
