"use client"

import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import * as z from "zod"

import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { toast } from "@/components/ui/use-toast"
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/react-hook-form/form"

import { useConfigStore } from "../store"

const AIConfigFormSchema = z.object({
  token: z.string().min(2, {
    message: "Name must be at least 2 characters.",
  }),
  autoRunScope: z.array(z.string()),
})

export type AIConfigFormValues = z.infer<typeof AIConfigFormSchema>
export const AutoRunScopes = ["SQL.SELECT", "SQL.INSERT", "D3.CHART"]
// This can come from your database or API.
const defaultValues: Partial<AIConfigFormValues> = {
  // name: "Your name",
  // dob: new Date("2023-01-23"),
  autoRunScope: [],
}

export function AIConfigForm() {
  const { setAiConfig, aiConfig } = useConfigStore()
  const form = useForm<AIConfigFormValues>({
    resolver: zodResolver(AIConfigFormSchema),
    defaultValues: {
      ...defaultValues,
      ...aiConfig,
    },
  })

  function onSubmit(data: AIConfigFormValues) {
    setAiConfig(data)
    toast({
      title: "You submitted the following values:",
      description: (
        <pre className="mt-2 w-[340px] rounded-md bg-slate-950 p-4">
          <code className="text-white">{JSON.stringify(data, null, 2)}</code>
        </pre>
      ),
    })
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
        <FormField
          control={form.control}
          name="token"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Token</FormLabel>
              <FormControl>
                <Input placeholder="OpenAI API Token" {...field} />
              </FormControl>
              <FormDescription>
                This is the token used to access the OpenAI API.
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="autoRunScope"
          render={() => (
            <FormItem>
              <div className="mb-4">
                <FormLabel className="text-base">Auto Run Code(Beta)</FormLabel>
                <FormDescription>
                  If enabled, the code generated by the AI will be automatically
                  run.
                </FormDescription>
              </div>
              {AutoRunScopes.map((_item) => (
                <FormField
                  key={_item}
                  control={form.control}
                  name="autoRunScope"
                  render={({ field }) => {
                    return (
                      <FormItem
                        key={_item}
                        className="flex flex-row items-start space-x-3 space-y-0"
                      >
                        <FormControl>
                          <Checkbox
                            checked={field.value?.includes(_item)}
                            onCheckedChange={(checked: any) => {
                              return checked
                                ? field.onChange([...field.value, _item])
                                : field.onChange(
                                    field.value?.filter(
                                      (value) => value !== _item
                                    )
                                  )
                            }}
                          />
                        </FormControl>
                        <FormLabel className="font-normal">{_item}</FormLabel>
                      </FormItem>
                    )
                  }}
                />
              ))}
              <FormMessage />
            </FormItem>
          )}
        />
        <Button type="submit">Update Config</Button>
      </form>
    </Form>
  )
}
