/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bc6c7a86e9a17aa0eb339291b3f212de)
interface __BaseEnv_Env {
  AUTH_USERINFO_URL:
    | "https://staging.eidos.space/api/auth/oauth2/userinfo"
    | "https://eidos.space/api/auth/oauth2/userinfo"
  CONTROL_ORIGIN: "https://relay-staging.eidos.ink" | "https://relay.eidos.ink"
  PUBLIC_HOST_LABEL_SUFFIX: "-staging" | ""
  PUBLIC_HOST_SUFFIX: "eidos.ink"
  TUNNELS: DurableObjectNamespace<import("./src/index").TunnelDurableObject>
  EIDOS_ACCOUNT: Fetcher /* eidos-space-staging */ | Fetcher /* eidos-space */
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index")
    durableNamespaces: "TunnelDurableObject"
  }
  interface StagingEnv {
    AUTH_USERINFO_URL: "https://staging.eidos.space/api/auth/oauth2/userinfo"
    CONTROL_ORIGIN: "https://relay-staging.eidos.ink"
    PUBLIC_HOST_LABEL_SUFFIX: "-staging"
    PUBLIC_HOST_SUFFIX: "eidos.ink"
    TUNNELS: DurableObjectNamespace<import("./src/index").TunnelDurableObject>
    EIDOS_ACCOUNT: Fetcher /* eidos-space-staging */
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "AUTH_USERINFO_URL"
      | "CONTROL_ORIGIN"
      | "PUBLIC_HOST_LABEL_SUFFIX"
      | "PUBLIC_HOST_SUFFIX"
    >
  > {}
}
