import type { MarkdownEditorLabels } from "@eidos.space/markdown"

/** Site-owned translations through the public component API. */
export const chineseEditorLabels = {
  paragraph: "正文",
  heading1: "一级标题",
  heading2: "二级标题",
  heading3: "三级标题",
  quote: "引用",
  codeBlock: "代码块",
  bulletList: "无序列表",
  numberedList: "有序列表",
  checkList: "任务列表",
  bold: "加粗",
  italic: "斜体",
  strikethrough: "删除线",
  highlight: "高亮",
  inlineCode: "行内代码",
  undo: "撤销",
  redo: "重做",
  saveBlock: "保存",
  cancelBlockEdit: "取消",
  insertBlock: "插入内容块",
  insertInline: "插入行内内容",
  addBlockBelow: "在下方添加内容块",
  dragBlock: "拖动内容块",
  insert: "插入",
  basicBlocks: "基础内容",
  extendedBlocks: "扩展内容",
  mathBlock: "块级公式",
  inlineMath: "行内公式",
  frontmatter: "文档属性",
  image: "图片",
  footnote: "脚注",
  rawHtml: "HTML",
  table: "表格",
  divider: "分隔线",
  frontmatterAlreadyExists: "已添加文档属性",
  backToInsertMenu: "返回插入菜单",
  emptyMathBlock: "添加 TeX 公式",
  emptyImageBlock: "添加图片",
  frontmatterYaml: "YAML 文档属性",
  footnoteText: "脚注内容",
  htmlSource: "HTML 源码",
  formulaSource: "TeX 公式源码",
  filterBlocks: "筛选内容块…",
  filterInline: "筛选行内命令…",
  noMatchingBlocks: "没有匹配的内容块",
  noMatchingInlineCommands: "没有匹配的行内命令",
  insertMenuHint: "在空行输入 / 打开此菜单",
  inlineMenuHint: "在光标处插入行内内容",
} satisfies MarkdownEditorLabels
