import type { BuiltInMarkdownProfileId } from "@eidos.space/markdown"

export type SyntaxExample = {
  id: string
  en: string
  zh: string
  group: "CommonMark" | "GFM" | "Extended" | "Vault"
  source: string
  presets: readonly BuiltInMarkdownProfileId[]
  mode: "rich" | "semantic" | "safe" | "host"
}
const all = ["gfm", "eidos", "obsidian"] as const
const extended = ["eidos", "obsidian"] as const
const vault = ["obsidian"] as const

/** Representative source fixtures. These describe families, not a conformance score. */
export const syntaxExamples: readonly SyntaxExample[] = [
  {
    id: "paragraph",
    en: "Paragraphs & soft breaks",
    zh: "段落与软换行",
    group: "CommonMark",
    source: "A paragraph with a soft\nline break.\n\nA second paragraph.",
    presets: all,
    mode: "rich",
  },
  {
    id: "heading",
    en: "ATX headings (1–6)",
    zh: "ATX 标题（1–6 级）",
    group: "CommonMark",
    source:
      "# Heading 1\n\n## Heading 2\n\n### Heading 3\n\n#### Heading 4\n\n##### Heading 5\n\n###### Heading 6",
    presets: all,
    mode: "rich",
  },
  {
    id: "setext",
    en: "Setext headings",
    zh: "Setext 标题",
    group: "CommonMark",
    source: "Heading one\n===========\n\nHeading two\n-----------",
    presets: all,
    mode: "semantic",
  },
  {
    id: "quote",
    en: "Block quotes & nesting",
    zh: "引用与嵌套引用",
    group: "CommonMark",
    source: "> A quotation.\n>\n> > A nested **quotation**.",
    presets: all,
    mode: "rich",
  },
  {
    id: "bullet-list",
    en: "Bulleted lists",
    zh: "无序列表",
    group: "CommonMark",
    source: "- First item\n- Second item\n  - Nested item",
    presets: all,
    mode: "rich",
  },
  {
    id: "ordered-list",
    en: "Ordered lists & starting numbers",
    zh: "有序列表与起始编号",
    group: "CommonMark",
    source: "3. Third item\n4. Fourth item\n   1. Nested item",
    presets: all,
    mode: "rich",
  },
  {
    id: "list-blocks",
    en: "Loose lists & nested blocks",
    zh: "松散列表与块级内容",
    group: "CommonMark",
    source:
      "1. First paragraph.\n\n   Another paragraph.\n\n   ```js\n   const answer = 42\n   ```\n\n2. Next item.",
    presets: all,
    mode: "rich",
  },
  {
    id: "thematic-break",
    en: "Thematic breaks",
    zh: "分隔线",
    group: "CommonMark",
    source: "Before\n\n---\n\nAfter",
    presets: all,
    mode: "rich",
  },
  {
    id: "fenced-code",
    en: "Fenced code & language",
    zh: "围栏代码与语言标记",
    group: "CommonMark",
    source:
      "```ts\nconst document = { format: 'markdown' }\n```\n\n~~~text\nAlternative fence\n~~~",
    presets: all,
    mode: "rich",
  },
  {
    id: "indented-code",
    en: "Indented code",
    zh: "缩进代码块",
    group: "CommonMark",
    source: "    const answer = 42\n    console.log(answer)",
    presets: all,
    mode: "semantic",
  },
  {
    id: "emphasis",
    en: "Emphasis & strong emphasis",
    zh: "斜体与粗体",
    group: "CommonMark",
    source:
      "*Emphasis*, **strong**, and ***both***.\n\n_Emphasis_ and __strong__.",
    presets: all,
    mode: "rich",
  },
  {
    id: "code-span",
    en: "Code spans",
    zh: "行内代码",
    group: "CommonMark",
    source: "Use `inline code`, or `` a `backtick` inside ``.",
    presets: all,
    mode: "rich",
  },
  {
    id: "link",
    en: "Inline links & titles",
    zh: "行内链接与标题",
    group: "CommonMark",
    source: '[Markdown](https://eidos.space "Visit Eidos")',
    presets: all,
    mode: "rich",
  },
  {
    id: "reference-link",
    en: "Reference links & definitions",
    zh: "引用式链接与定义",
    group: "CommonMark",
    source:
      '[Full][guide], [guide][], and [guide].\n\n[guide]: https://eidos.space "Guide"',
    presets: all,
    mode: "semantic",
  },
  {
    id: "autolink",
    en: "URL & email autolinks",
    zh: "网址与邮箱自动链接",
    group: "CommonMark",
    source: "<https://eidos.space> and <hello@example.com>",
    presets: all,
    mode: "semantic",
  },
  {
    id: "image",
    en: "Images & reference images",
    zh: "图片与引用式图片",
    group: "CommonMark",
    source:
      '![Eidos](https://editor.eidos.space/eidos-file-icon-192.png "Eidos")\n\n![Eidos][icon]\n\n[icon]: https://editor.eidos.space/eidos-file-icon-192.png',
    presets: all,
    mode: "semantic",
  },
  {
    id: "hard-break",
    en: "Hard line breaks",
    zh: "硬换行",
    group: "CommonMark",
    source: "Two spaces here.  \nNext line.\\\nAnother line.",
    presets: all,
    mode: "rich",
  },
  {
    id: "escapes",
    en: "Backslash escapes",
    zh: "反斜杠转义",
    group: "CommonMark",
    source: "\\*Not italic\\* and \\[not a link\\].",
    presets: all,
    mode: "rich",
  },
  {
    id: "entities",
    en: "Character references",
    zh: "字符引用",
    group: "CommonMark",
    source: "&amp; &copy; &#35; &#x23;",
    presets: all,
    mode: "rich",
  },
  {
    id: "html",
    en: "Raw HTML & comments",
    zh: "HTML 与注释",
    group: "CommonMark",
    source:
      "<details>\n<summary>More information</summary>\n<p>Safe <strong>HTML</strong>.</p>\n</details>\n\n<!-- Source-only comment -->",
    presets: all,
    mode: "safe",
  },
  {
    id: "table",
    en: "Tables, alignment & escaped pipes",
    zh: "表格、对齐与管道符转义",
    group: "GFM",
    source:
      "| Left | Center | Right |\n| :--- | :---: | ---: |\n| A \\| B | **Bold** | 42 |\n| Next | `code` | 7 |",
    presets: all,
    mode: "rich",
  },
  {
    id: "task-list",
    en: "Task lists",
    zh: "任务列表",
    group: "GFM",
    source: "- [x] Completed\n- [ ] Next step\n  - [ ] Nested task",
    presets: all,
    mode: "rich",
  },
  {
    id: "strikethrough",
    en: "Strikethrough",
    zh: "删除线",
    group: "GFM",
    source: "~~An old idea~~ A better idea.",
    presets: all,
    mode: "rich",
  },
  {
    id: "extended-autolink",
    en: "Extended URL & email autolinks",
    zh: "扩展网址与邮箱自动链接",
    group: "GFM",
    source:
      "Visit www.example.com, https://example.com/a_(b), or write hello@example.com.",
    presets: all,
    mode: "semantic",
  },
  {
    id: "tag-filter",
    en: "Disallowed raw HTML",
    zh: "禁用的 HTML 标签",
    group: "GFM",
    source:
      '<script>alert("never executed")</script>\n\n<iframe src="https://example.com"></iframe>',
    presets: all,
    mode: "safe",
  },
  {
    id: "frontmatter",
    en: "YAML document properties",
    zh: "YAML 文档属性",
    group: "Extended",
    source:
      "---\ntitle: A portable document\ntags: [writing, ideas]\n---\n\nBody text.",
    presets: extended,
    mode: "semantic",
  },
  {
    id: "footnote",
    en: "Footnotes & definition tail",
    zh: "脚注与文末定义",
    group: "Extended",
    source:
      "A sentence with a footnote.[^note]\n\n[^note]: Additional information.\n\nThis paragraph still precedes the rendered footnote.",
    presets: extended,
    mode: "semantic",
  },
  {
    id: "inline-math",
    en: "Inline equations",
    zh: "行内公式",
    group: "Extended",
    source: "Euler's identity: $e^{i\\pi} + 1 = 0$.",
    presets: extended,
    mode: "semantic",
  },
  {
    id: "block-math",
    en: "Block equations & math fences",
    zh: "块级公式与 math 围栏",
    group: "Extended",
    source:
      "$$\n\\int_0^1 x^2\\,dx = \\frac{1}{3}\n$$\n\n```math\na^2 + b^2 = c^2\n```",
    presets: extended,
    mode: "semantic",
  },
  {
    id: "highlight",
    en: "Highlights",
    zh: "文本高亮",
    group: "Extended",
    source: "Keep the ==important part== visible.",
    presets: extended,
    mode: "rich",
  },
  {
    id: "wikilink",
    en: "Wikilinks, aliases & anchors",
    zh: "双链、别名与锚点",
    group: "Vault",
    source: "[[Note]], [[Note|Alias]], [[Note#Heading]], [[Note#^block-id]].",
    presets: vault,
    mode: "host",
  },
  {
    id: "obsidian-image",
    en: "Attachment dimensions",
    zh: "附件尺寸",
    group: "Vault",
    source:
      "![Eidos|240x120](https://editor.eidos.space/eidos-file-icon-192.png)",
    presets: vault,
    mode: "host",
  },
  {
    id: "relative-link",
    en: "Vault-relative Markdown links",
    zh: "Vault 相对 Markdown 链接",
    group: "Vault",
    source: "[A local note](Notes/Example.md#Heading)",
    presets: vault,
    mode: "host",
  },
  {
    id: "embed",
    en: "Embeds",
    zh: "嵌入引用",
    group: "Vault",
    source: "![[Note#Heading]]\n\n![[attachments/photo.png|240x120]]",
    presets: vault,
    mode: "host",
  },
  {
    id: "callout",
    en: "Callouts & folding",
    zh: "提示块与折叠",
    group: "Vault",
    source: "> [!tip]- A useful note\n> A **collapsible** callout.",
    presets: vault,
    mode: "semantic",
  },
  {
    id: "tag",
    en: "Tags",
    zh: "标签",
    group: "Vault",
    source: "An idea about #writing and #work/project.",
    presets: vault,
    mode: "semantic",
  },
  {
    id: "comment",
    en: "Hidden comments",
    zh: "隐藏注释",
    group: "Vault",
    source: "Visible text %%a private drafting comment%% continues.",
    presets: vault,
    mode: "semantic",
  },
  {
    id: "block-id",
    en: "Block identifiers",
    zh: "块标识符",
    group: "Vault",
    source: "A paragraph with a stable identifier. ^stable-note",
    presets: vault,
    mode: "semantic",
  },
  {
    id: "inline-footnote",
    en: "Inline footnotes",
    zh: "行内脚注",
    group: "Vault",
    source: "An inline footnote ^[A short explanation.].",
    presets: vault,
    mode: "semantic",
  },
]
