import { FieldType } from "./const"

const computedFieldTypes = [FieldType.Formula, FieldType.Lookup, FieldType.Link]
const autoGeneratedFieldTypes = [FieldType.CreatedBy, FieldType.LastEditedBy, FieldType.CreatedTime, FieldType.LastEditedTime]
export const isComputedField = (columnType: FieldType) => {
  return computedFieldTypes.includes(columnType)
}

export const isAutoGeneratedField = (columnType: FieldType) => {
  return autoGeneratedFieldTypes.includes(columnType)
}
